config/routes.rb
ScorecardTest::Application.routes.draw do


  root "home#index"
  devise_for :users  
  resources :event
  resources :contestant
  resources :scorecard
  resources :user
end

app/models/event.rb
class Event < ActiveRecord::Base
  
  # has_many :contestants
  has_many :scorecards
  has_and_belongs_to_many :contestants
  has_and_belongs_to_many :users

  validates :name, presence: true, uniqueness: true
  validates :date, presence: true


  def self.make_date_from(year, month, day)
    date = Date.new(year.to_i, month.to_i, day.to_i)
  end

  def self.create_from_form(name, date, contestants, user)
    Event.create! do |event|
      event.name = name
      event.date = date
      contestants.each do |con|
        event.contestants << Contestant.find(con)
      end
        event.users << user
    end
    
  end

  def self.add_user_to_event(user, event)
    event.users << user
  end

  def display_date(date)
    date.to_s[5..-1] + "-" + date.to_s[0..3]
  end



end

app/controllers/event_controller.rb
class EventController < ApplicationController

  before_filter :authenticate_user!
  

  def index
    @events = Event.all
  end

  def show
    @user = current_user
    @users = Event.find(params[:id]).users
    @event = Event.find(params[:id])
    @scorecards = Scorecard.find_by_event_id(@event.id)
  end

  def create
    event_info = params[:event]
    contestant_ids = event_info[:contestant_ids]
    contestant_ids.pop
    @user = current_user
    event_date = Event.make_date_from(event_info.fetch("date(1i)"),event_info.fetch("date(2i)"),event_info.fetch("date(3i)"))
    @event = Event.create_from_form(event_info[:name], event_date, contestant_ids,  @user)

    # Contestant.set_event_from(contestant_ids, @event.id)

    @event.save

    redirect_to controller: :event, action: :index
    
  end

  def destroy
   if @event = Event.find(params[:id])
     @event.destroy
     redirect_to controller: :event, action: :index
   end

  end

  def new
    @event = Event.new
  end

  def edit
  end

  def remove

  end
  

  def update
    @user = current_user
    @event = Event.find(params[:id])
    User.add_event_to_user(@user, @event)
    redirect_to controller: :event, action: :show
  end

end

app/helpers/event_helper.rb
module EventHelper
end

app/views/event/_scorecards.html.erb
      <tr>
        <th>Contestant Number</th>
        <th>Name</th>
        <th>Written</th>
        <th>A Capela</th>
        <th>Grab Bag</th>
        <th>Beat Juggling</th>
        <th>Cypha</th>
        <th>Total</th>
      </tr>
      <% counter = 1 %>
      <% @event.contestants.each do |con| %>

      <tr>
            <td>
              <%= counter %>
            </td>
            <td>
              <%= con.name %>
            </td>
            <td>
              <%  if  con.find_sc_by_name_and_event_and_user(con.scorecards, "Written", @event, @user).nil? %>
                <%= link_to "Score this round", new_scorecard_path(param1: 'Written', param2: @event.id, param3: con.id) %>
              <% else %>
              <% sc = con.find_sc_by_name_and_event_and_user(con.scorecards, "Written", @event, @user) %>
              <%= sc.total %>
              <%= link_to "Edit Score", edit_scorecard_path(sc.id) %>
              <% end %>
            </td>
            <td>
              <%  if  con.find_sc_by_name_and_event_and_user(con.scorecards, "A Capela", @event, @user).nil? %>
                <%= link_to "Score this round", new_scorecard_path(param1: 'A Capela', param2: @event.id,  param3: con.id) %>
              <% else %>
              <% sc = con.find_sc_by_name_and_event_and_user(con.scorecards, "A Capela", @event, @user) %>
              <%= sc.total %>
              <%= link_to "Edit Score", edit_scorecard_path(sc.id) %>
              <% end %>
            </td>
            <td>
              <%  if  con.find_sc_by_name_and_event_and_user(con.scorecards, "Grab Bag", @event, @user).nil? %>
                <%= link_to "Score this round", new_scorecard_path(param1: 'Grab Bag', param2: @event.id,  param3: con.id) %>
              <% else %>
              <% sc = con.find_sc_by_name_and_event_and_user(con.scorecards, "Grab Bag", @event, @user) %>
              <%= sc.total %>
              <%= link_to "Edit Score", edit_scorecard_path(sc.id) %>
              <% end %>
            </td>
            <td>
              <%  if  con.find_sc_by_name_and_event_and_user(con.scorecards, "Beat Juggling", @event, @user).nil? %>
                <%= link_to "Score this round", new_scorecard_path(param1: 'Beat Juggling', param2: @event.id,  param3: con.id) %>
              <% else %>
              <% sc = con.find_sc_by_name_and_event_and_user(con.scorecards, "Beat Juggling", @event, @user) %>
              <%= sc.total %>
              <%= link_to "Edit Score", edit_scorecard_path(sc.id) %>
              <% end %>
            </td>
            <td>
              <%  if  con.find_sc_by_name_and_event_and_user(con.scorecards, "Cypha", @event, @user).nil? %>
                <%= link_to "Score this round", new_scorecard_path(param1: 'Cypha', param2: @event.id,  param3: con.id) %>
              <% else %>
              <% sc = con.find_sc_by_name_and_event_and_user(con.scorecards, "Cypha", @event, @user) %>
              <%= sc.total %>
              <%= link_to "Edit Score", edit_scorecard_path(sc.id) %>
              <% end %>
            </td>
            <td>
              <%= con.get_total_score_for_event(con.scorecards, @event, @user) %>
            </td> 
             <% counter=counter+1 %>
    <% end %>

app/views/event/create.html.erb
<h1>Event#create</h1>
<p>Find me in app/views/event/create.html.erb</p>

app/views/event/destroy.html.erb
<h1>Event#destroy</h1>
<p>Find me in app/views/event/destroy.html.erb</p>

app/views/event/edit.html.erb
<h1>Event#edit</h1>
<p>Find me in app/views/event/edit.html.erb</p>

app/views/event/index.html.erb
<h1>Events</h1>

<%= link_to "Create New Event", new_event_path %>
<p>
  <ul id="full_event_list">
<% @events.each do |event| %>
<li id="event_name"><b> <%= event.name %></b> <span class="event_date_span"><%= event.display_date(event.date) %></span> </br>
  <%= link_to "Score this Event", event_path(event) %> ||  <%= link_to "Total Scores", scorecard_path(event.id) %>
  
  <% if current_user.admin? %>
    <%= button_to "Delete Event", event_path(event.id), method: :delete, confirm: "Are you sure you want to delete #{event.name}?"   %> 
  <% end %>


</li>
<% end %>
</ul>
</p>

app/views/event/new.html.erb
<h1>New Event</h1>


<%= simple_form_for(@event, url: {action: :create, controller: :event}, method: :post) do |f| %>
  <%= f.input :name  %>
  <%= f.input :date  %>
  <%= f.association :contestants, as: :check_boxes %>
  <%= f.submit "Create" %>

<% end %>

app/views/event/show.html.erb
<div class="container" id="contestants_list">
  
  <h1><%= @event.name %></h1>
  <% if current_user.admin? %>
    <div class="container col-md-4">
      <h1>Contestants</h1>
        <ol>
          <% @event.contestants.each do |c| %>
          <li> <%= c.name %> </li>
          <% end %>
          <%= link_to "Add Contestant", contestant_index_path %>
        </ol>
    </div>

    <div class="container col-md-4 ">
      <h1>Judges</h1>
        <ul>
          <% @users.each do |u| %>
          <li> <%= u.name %> <%= button_to "Remove this Judge", user_path(user_id:  u.id, event_id: @event.id ),  method: :put, confirm: "This will remove the judge from the event and delete all scorecards associated"  %></li>
          <% end %>
          
        </ul>
    </div>

    <div class="container col-md-4">
      <h1>Rounds</h1>
        <ul>
          <li>Round 1: Written</li>
          <li>Round 2: A Capela</li>
          <li>Round 3: Grab Bag</li>
          <li>Round 4: Beat Juggling</li>
          <li>Round 5: Cypha</li>
        </ul>
    </div>
  <% end %> <!-- checks if user an admin -->
</div>


<div class="container">
  <table class="table table-bordered table-striped table-hover table-responsive" id="scorecard_table">
     <% if !@event.users.include?(@user) %>
         <%= simple_form_for(@event, url: {controller: :event, action: :update}, mehtod: :put) do |f| %>
        <%= f.submit "Judge Event" %>
        <% end %>
        <% else %>
        <%= render 'scorecards' %>

        <% end %>


       
     
  </table>
</div>