config/routes.rb
ScorecardTest::Application.routes.draw do


  root "home#index"
  devise_for :users  
  resources :event
  resources :contestant
  resources :scorecard
  resources :user
end

app/models/contestant.rb
class Contestant < ActiveRecord::Base

validates :name, presence: true, uniqueness: true
# belongs_to :event
has_many :scorecards
has_and_belongs_to_many :events


  def self.create_from_params(name)
    create! do |c|
      c.name = name
    end
  end

  def add_event_to(contestant, event)
    Contestant.find(contestant).events << Event.find(event)
  end


  def find_sc_by_name_and_event(scorecards, name, event)
    scorecards.detect{ |sc| sc.name == name && sc.event.id == event.id}
  end

  def find_sc_by_name_and_event_and_user(scorecards, name, event, user)
    scorecards.detect{ |sc| sc.name == name && sc.event.id == event.id && sc.user.id == user.id}
  end

  def score_event(scorecards, event, user)
    score = 0
    scorecards.each do |sc|
      if (sc.event.id == event.id && sc.user.id == user.id)
        score = score + sc.total
      end 
    end
    score
  end

  def get_total_score_for_the_event(scorecards, event)

    
    score = 0
    scorecards.each do |sc|
      if (sc.event.id == event.id)
        score = score + sc.total
      end
    end  
    score
  end

  def total_score(scorecards, event, users)
    score = 0
    users.each do |j|
      score = score + score_event(scorecards, event, j)
    end
  score
  end


  def get_total_score_for_event(scorecards, event, user)

    
    score = 0
    scorecards.each do |sc|
      if (sc.event.id == event.id && sc.user.id == user.id)
        score = score + sc.total
      end
    end  
    score
  end


end

app/controllers/contestant_controller.rb
class ContestantController < ApplicationController
  before_filter :authenticate_user!
  before_action :check_admin?

  def new
  end

  def show
    @contestant = Contestant.find(params[:id])
  end

  def index
    @contestants = Contestant.all
    @events = Event.all
  end

  def edit
    @contestant = Contestant.find(params[:id])
      params[:contestant][:event_ids].pop
    @contestant.add_event_to(@contestant, params[:contestant][:event_ids])
    @contestant.save!

    redirect_to controller: :contestant, action: :index
  end

  def new
    @contestant = Contestant.new
  end

  def create
    @contestant = Contestant.create_from_params(params[:contestant][:name])
    redirect_to controller: :contestant, action: :index
  end


  def destroy
    if @contestant = Contestant.find(params[:id])
     @contestant.destroy
     redirect_to controller: :contestant, action: :index
   end
  end


  private

  def check_admin?
    if current_user.admin?
      true
    else
      redirect_to controller: :event, action: :index
    end

  end
end

app/helpers/contestant_helper.rb
module ContestantHelper
end

app/views/contestant/destroy.html.erb
<h1>Contestant#destroy</h1>
<p>Find me in app/views/contestant/destroy.html.erb</p>

app/views/contestant/edit.html.erb
<h1>Contestant#edit</h1>
<p>Find me in app/views/contestant/edit.html.erb</p>

app/views/contestant/index.html.erb
<h1>Contestant</h1>

<%= link_to "Add New Contestant", new_contestant_path %>
<p>
  <ul>
<% @contestants.each do |c| %>
 <li> <%= link_to c.name, contestant_path(c) %> <%= button_to "Delete Contestant", contestant_path(c.id), method: :delete %> </li>
<% end %>
</ul>
</p>

app/views/contestant/new.html.erb
<h1>New Contestant</h1>


<%= simple_form_for(@contestant, url: {action: :create, controller: :contestant}, method: :post) do |f| %>
  <%= f.input :name  %>
  <%= f.submit "Create" %>

<% end %>

app/views/contestant/show.html.erb
<h1><%= @contestant.name %></h1>


<div>
  <% if  @contestant.events.empty? %>
  <p>
    Assign this contestant to an event.
    <%= simple_form_for(@contestant, url: {action: :edit, controller: :contestant}, method: :get) do |f| %>
      <%= f.association :events, as: :radio_buttons %>
      <%= f.submit "Add" %>
    <% end %>
  </p>  
  <% else %><strong>Events: </strong>
    <% @contestant.events.each do |event| %>
      *<%= event.name %>*
    <% end %>

    </br>
    </br>
    </br>
    </br>
    
    Add this contestant to additional events:
        <%= simple_form_for(@contestant, url: {action: :edit, controller: :contestant}, method: :get) do |f| %>
      <%= f.association :events, as: :check_boxes %>
      <%= f.submit "Add" %>
    <% end %>
  <% end %>
</div>