config/routes.rb
ScorecardTest::Application.routes.draw do


  root "home#index"
  devise_for :users  
  resources :event
  resources :contestant
  resources :scorecard
  resources :user
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScorecardTest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body data-no-turbolink="true">

  <nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" >
      <ul class="nav navbar-nav">
        <li><%= link_to image_tag("logo.jpeg"), root_path  %></li>
       <li><%= link_to "Events", event_index_path %> </li>
       <li><%= link_to "Contestants", contestant_index_path %></li>
       <li><%= link_to "Judges", user_index_path %></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right"> 
        <% if user_signed_in? %>
          <li>Signed in as: <%= current_user.name %></li>
         <% else %>
           <li><%= link_to "Sign Up", new_user_registration_path %></li>
           <li><%= link_to "Sign In", new_user_session_path %></li>
       <% end %>
       <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li> 
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

   <p class=" alert"><%= notice %></p>
   <p class="alert"><%= alert %></p>
<div class= "container">
  <%= yield %>
</div>

</body>
</html>